fix: multi arch build with buildkit always enabled
konveyor/move2kube-api pull request #112
Opened 2022-07-13 16:06 UTC by kmehant

Signed-off-by: Mehant Kammakomati <kmehant@gmail.com>

platform environment various `TARGETPLATFORM`, `TARGETOS`, `TARGETARCH` are only available when the `docker build` is run using `buildkit`. 

In this PR, 
* we are enabling buildkit for all our docker image builds
* Replaced `TARGETPLATFORM` with much useful `TARGETOS`, `TARGETARCH` environment variables

✅ Empirically tested on my fork's github workflow.

2022-07-13 16:06 UTC, kmehant commented
@ashokponkumar @HarikrishnanBalagopal Please review!

2022-07-13 20:10 UTC, ashokponkumar reviewed
Will enabling buildkit for normal docker build cause any other side effects? Will this be an acceptable solution for normal users who might say do make cbuild?

2022-07-13 20:15 UTC, ashokponkumar requested changes

2022-07-13 20:15 UTC, ashokponkumar commented on Dockerfile
> +ARG TARGETARCH
Can we possibly set some common defaults like amd64, so that for those who don't enable buildkit the build does not fail?

2022-07-14 05:34 UTC, kmehant commented
@ashokponkumar I have made the changes.

2022-07-14 11:21 UTC, ashokponkumar approved these changes

2022-07-14 11:21 UTC, merged