fix: Update Golang version in Makefile to prevent cbuild failure
konveyor/move2kube-api pull request #161
Opened 2024-03-14 04:25 UTC by Akash-Nayak

Fixes: https://github.com/konveyor/move2kube-api/issues/160

Signed-off-by: Akash Nayak <akash19nayak@gmail.com>

2024-03-14 05:05 UTC, kmehant requested changes
@Akash-Nayak Can you also bump up the version on README? 

https://github.com/konveyor/move2kube-api/blob/main/README.md?plain=1#L24

2024-03-14 05:40 UTC, Akash-Nayak commented
> @Akash-Nayak Can you also bump up the version on README?
> 
> https://github.com/konveyor/move2kube-api/blob/main/README.md?plain=1#L24
 
 Thanks @kmehant ! Done.

2024-03-14 05:42 UTC, kmehant approved these changes

2024-03-20 14:38 UTC, HarikrishnanBalagopal approved these changes
LGTM

2024-03-20 14:38 UTC, merged